---
# tasks file for app-update
- name: Bundle
  command: bash -lc "bundle install --without development test"
  register: bundle_install_task
  args:
    chdir: "{{ app_path }}"

- debug: var=bundle_install_task.stdout_lines
- debug: var=bundle_install_task.stderr_lines
  when: bundle_install_task is failed


- name: Asset Compile
  command: bash -lc "rails webpacker:compile"
  args:
    chdir: "{{ app_path }}"
  register: asset_compile_task

- debug: var=asset_compile_task.stdout_lines
- debug: var=asset_compile_task.stderr_lines
  when: asset_compile_task is failed
