- hosts: "{{target_host}}"
  vars:
    app_name: "EcommerceAPI"
    app_path: "{{ base_path }}/{{ app_environment }}"
    repo_url: "{{ base_repo_url }}/{{ app_name }}.git"
  roles:
    - rails-app-update
    - rails-db-update
    - rails-app-restart
    - nginx-restart
