---
# tasks file for git-action-before-app-update
- name: Git Fetch All From Origin
  command: git -c credential.helper='!f() { echo "username={{ gituser }}"; echo "password={{ gitpassword }}"; }; f cache --timeout=60' fetch origin
  register: git_fetch_task
  args:
    chdir: "{{ app_path }}"

- debug: var=git_fetch_task.stdout_lines
- debug: var=git_fetch_task.stderr_lines
  when: git_fetch_task is failed


- name: Git Switch To Target Branch
  when: (gitversion is defined) and (gitversion|length > 0)
  command: git checkout "{{ gitversion }}"
  register: git_switch_task
  args:
    chdir: "{{ app_path }}"

- debug: var=git_switch_task.stdout_lines
- debug: var=git_switch_task.stderr_lines
  when: git_switch_task is failed


- name: Git Pull from Version Control
  command: git -c credential.helper='!f() { echo "username={{ gituser }}"; echo "password={{ gitpassword }}"; }; f cache --timeout=60' pull
  register: git_pull_task
  args:
    chdir: "{{ app_path }}"

- debug: var=git_pull_task.stdout_lines
- debug: var=git_pull_task.stderr_lines
  when: git_pull_task is failed
